train_file: train_split_1_1.csv
val_file: val_split_1_1.csv
csv_path: stratified_smoke
batch_size: 10
num_workers: 0
epochs: 1
lr: 0.003000
weight_decay: 0.000010
device_count: 1
threshold: 0.500000
bandwidth: